server:
  port: 8080

eureka:     #tells about the eureka server details and its refresh time
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

  spring:
    application:
      name: eurekaclient #current service name to be used by the eureka serever

  management:
    security:
      enabled:  false #diable the spring security on the management endpoints

  logging:
    level:
      com.springtask.eurekaclien: DEBUG